docs/apis.json
docs/control.extend.md
docs/control.md
docs/defaults.md
docs/destroy.md
docs/element.md
docs/eventDescription.md
docs/eventHandler.md
docs/on.md
docs/options.md
docs/processors.md
docs/setup.md

Fixes lengths and makes its parent be can-legacy

Update the documentation

---

docs/control.md

document view instead of template

---

can-control.js
can-control_test.js
package.json
test.html
test/test.html

Closes https://github.com/canjs/can-control/issues/3.

Event rebinding

---

can-control.js
can-control_test.js
docs/control.extend.md
docs/control.md
docs/element.md

Closes https://github.com/canjs/can-control/issues/14.

Element binding

---

can-control_test.js

Closes https://github.com/canjs/can-control/issues/21.

Fixing tests in IE10

---

can-control_test.js

Closes https://github.com/canjs/can-control/issues/24.

updating test to not modify document.body

---

.gitignore
docs/control.md

Set bit-docs @parent to can-infrastructure

---

build.js
can-control.js
can-control_test.js
package.json

Part of https://github.com/canjs/canjs/issues/2747.

Can namespace

---

can-control_test.js

closes https://github.com/canjs/can-control/issues/49.

removing console.log

---

can-control.js
can-control_test.js

closes https://github.com/canjs/can-control/issues/57.

prevent errors when domData is deleted before control is destroyed

---

can-control.js
can-control_test.js

- Removed creating a div and instead shows a dev error and then return

54 - Creating an instance of a named control without passing an element

---

can-control.js
can-control_test.js

Resolves canjs/can-component#92

Add beforeremove to the set of common events

---

can-control.js
can-control_test.js

Make control add class to converted element instead of passed in element

---

LICENSE
package.json

The description guess on NPM looked icky.

Fix description and add LICENSE

---

can-control.js
docs/control.md

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/chasenlehara/e754bc6b6e8cdda69814372a33dfac80**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Update docs with new @parent & @collection

---

.jshintrc
can-control.js

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/Aosanders/245a21b2685ea9e063090206d59386eb**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Adds use strict. Fixes canjs/canjs#4217

---

can-control.js

Fixes for IE, where Document doesn't inherit methods from Node.

Use documentElement.contains()

---

can-control.js
can-control_test.js
package.json

Fix failure in environments with no documentElement

---

can-control_test.js
package.json

This pull request was created with [Landscaper](https://github.com/bitovi/landscaper).
The following code mods were used to create this PR:
1. **https://gist.github.com/cherifGsoul/e82fd3546da2c3bdabe4b4b9c918d361**
Please review this PR carefully as Landscaper does not guarantee any code mod's quality.

Landscaper: QUnit2 upgrade

---

can-control_test.js
package.json

No can-util
